// package o5genimpl is used by the code generated by
// protoc-gen-go-o5-messaging, exported types are used by the generated code
// only, are not intended for use by the library consumer and will not be
// treated as part of the public API for semantic versioning.

package o5genimpl
